### ISSUE TITLE
Feature Request: Auto Casting C-types

### ISSUE THREAD

**Issue by byehack** [ynkdir/py-win32more#4]
In continue of https://github.com/ynkdir/py-win32more/issues/2#issuecomment-1465049680

All functions are typed for both arguments and results. but current behavior is, it'll raise if our entered arguments types are not exact same as specified.

proposed behavior is that it should auto casting the types for both arguments and results.

here is current working script:
```py
from Windows.Win32.System.Rpc import RpcStringBindingComposeW
from Windows import UInt16, c_wchar_p
from ctypes import POINTER, cast

strBinding = cast(c_wchar_p(), POINTER(UInt16))
rStatus = RpcStringBindingComposeW(
    cast(c_wchar_p("0767a036-0d22-48aa-ba69-b619480f38cb"), POINTER(UInt16)),
    cast(c_wchar_p("ncalrpc"), POINTER(UInt16)),
    None,
    None,
    None,
    strBinding)
strBinding = cast(strBinding, c_wchar_p)

print(rStatus, strBinding.value)
```
Auto Casting will remove cast from our side:
```py
from Windows.Win32.System.Rpc import RpcStringBindingComposeW
from Windows import UInt16, c_wchar_p

strBinding = c_wchar_p()
rStatus = RpcStringBindingComposeW(
    c_wchar_p("0767a036-0d22-48aa-ba69-b619480f38cb"),
    c_wchar_p("ncalrpc"),
    None,
    None,
    None,
    strBinding)
print(rStatus, strBinding.value)
```

**Comment by byehack** [comment]
> Auto Casting will remove cast from our side:
> 
> ```python
> from Windows.Win32.System.Rpc import RpcStringBindingComposeW
> from Windows import UInt16, c_wchar_p
> 
> strBinding = c_wchar_p()
> rStatus = RpcStringBindingComposeW(
>     c_wchar_p("0767a036-0d22-48aa-ba69-b619480f38cb"),
>     c_wchar_p("ncalrpc"),
>     None,
>     None,
>     None,
>     strBinding)
> print(rStatus, strBinding.value)
> ```


And if we assume `string object` type is `c_wchar_p` and `byte object` type is `c_char_p`, we can have even simpler call:
```py
from Windows.Win32.System.Rpc import RpcStringBindingComposeW
from Windows import c_wchar_p

strBinding = c_wchar_p()
rStatus = RpcStringBindingComposeW("0767a036-0d22-48aa-ba69-b619480f38cb", "ncalrpc", None, None, None, strBinding)
print(rStatus, strBinding.value)
```
I think this is current behavior in `ctypes` module when we are calling a typed function.

**Comment by ynkdir** [comment]
WIP
I have not confirmed yet that if getting pointer value with byref(c_wchar_p()) is safe.

**Comment by ynkdir** [comment]
It seems to work.
I merged fix.
Could you confirm that works for you.

**Comment by byehack** [comment]
That's great, I can confirm both WIP examples above have been tested and passed successfully,

**Comment by byehack** [comment]
Reopened bcz still need to work to be complete. Look at this example (you can try to repro):

currently working script:
```py
from Windows.Win32.System.Rpc import RPC_SECURITY_QOS_V3_W
from Windows.Win32.Security import CreateWellKnownSid, WELL_KNOWN_SID_TYPE_WinLocalSystemSid
from ctypes import cast, c_ulong, c_void_p, create_string_buffer

SECURITY_MAX_SID_SIZE = 68
sidSize = c_ulong(SECURITY_MAX_SID_SIZE)
sid = create_string_buffer(SECURITY_MAX_SID_SIZE)
rStatus = CreateWellKnownSid(
    WELL_KNOWN_SID_TYPE_WinLocalSystemSid,
    None,
    sid,
    sidSize)
if not rStatus:
    raise
security = RPC_SECURITY_QOS_V3_W()
security.Sid = cast(sid, c_void_p)
```
Expected Work with auto casting:

```py
from Windows.Win32.System.Rpc import RPC_SECURITY_QOS_V3_W
from Windows.Win32.Security import CreateWellKnownSid, WELL_KNOWN_SID_TYPE_WinLocalSystemSid
from ctypes import cast, c_ulong, c_void_p, create_string_buffer

SECURITY_MAX_SID_SIZE = 68
sidSize = SECURITY_MAX_SID_SIZE
sid = create_string_buffer(SECURITY_MAX_SID_SIZE)
rStatus = CreateWellKnownSid(
    WELL_KNOWN_SID_TYPE_WinLocalSystemSid,
    None,
    sid,
    sidSize) # not work after removed c_ulong
if not rStatus:
    raise
security = RPC_SECURITY_QOS_V3_W()
security.Sid = sid # not work after removed cast
```

**Comment by byehack** [comment]
^^^ This PR still not able to to cover removed `cast(sid, c_void_p)`

**Comment by byehack** [comment]
In continue of https://github.com/ynkdir/py-win32more/pull/8 I decided to create a TODO list to improve auto casting:

- [x] Parameters Pointers
- [x] Parameters Unions
- [ ] Other types of Parameters
- [ ] Results Pointers
- [ ] Results Unions
- [ ] Other types of Results

**Comment by byehack** [comment]
https://github.com/ynkdir/py-win32more/blob/c723275857ab6d104aa6afed2e731132f9de9a74/Windows/__init__.py#L65-L74

the function name is `easycast` but it has 2 more different abilities:

1. it's convert related types in python object to c-type object: `c_wchar_p(obj)` at line 68.
2. second is `pointer(obj)` at line 73.

I think these 2 should break into separate functions. if I had time, I'll send a PR for these.

**Comment by ynkdir** [comment]
>    sidSize) # not work after removed c_ulong

For `POINTER(c_int)` type, it is ambiguous that `int` should be converted as `cast(123, POINTER(c_int))` or `pointer(c_int(123))`.
I guess it is better to keep as is for now.

**Comment by mominshaikhdevs** [comment]
what's the latest update on this?

**Comment by ynkdir** [comment]
I am still not sure how it should be.
